config/routes.rb
LicitacoesFinder::Application.routes.draw do
  match as: 'xls', via: :get, '/xls' => 'licitacaos#xls'
  match as: 'pdf', via: :get, '/pdf' => 'licitacaos#pdf'
  match as: 'atualiza_tudo', via: :get, '/atualiza/tudo' => 'licitacaos#atualizar_tudo'
  match as: 'atualiza_parcial', via: :get, '/atualiza/parcial' => 'licitacaos#atualizar_parcial'
  match as: 'pesquisa', via: :get, '/pesquisa' => 'licitacaos#pesquisar' 
  match as: 'nao_exibe_objetos', via: :get, '/nao_exibe_objetos' => 'licitacaos#nao_exibe_objetos' 
  root :to => 'home#index'
  resources :filtros, :path => 'home#index'
  match as: 'salvar_filtro', via: :post, 'filtro/salvar' => 'filtros#salvar'

end

app/controllers/home_controller.rb
# encoding: UTF-8
require "will_paginate"
require "pdf_generator"

class HomeController < ApplicationController
	@@ORDENACAO = 'DATE(updated_at) DESC, data_abertura DESC, municipio'
	def index
		@filtros = Filtro.order(:descricao)
        	if session[:acao]
    	    	@licitacaos = Licitacao.where( session[:licitacaos_where] ).order(@@ORDENACAO)
           		send "gera_#{session[:acao]}"
        	else
           		gera_lista
	end
	end
private
	def gera_xls
	    @filtro = Filtro.new(session[:filtro])
	    session[:acao] = nil
	    session[:licitacaos_where] = nil
	    session[:data_abertura_inicial] = nil
	    session[:data_abertura_final] = nil
	    session[:filtro] = nil
	    session[:municipio] = nil
        separador = "|"
	    xls = "Data de Abertura#{separador}Município#{separador}Código#{separador}Objeto#{separador}Criado#{separador}Atualizado#{separador}Link"
	    @licitacaos.each do |l|
            xls += "\n"
	        xls += l.to_xls(separador).delete("\n").delete("\r")
        end
        send_data xls, filename: "licitacoes.xls"	
	end
	def gera_pdf
		@filtro = Filtro.new(session[:filtro])
		dados_da_pesquisa = {
			:keywords => @filtro.keywords,
			:data_abertura_inicial => session[:data_abertura_inicial],
			:data_abertura_final => session[:data_abertura_final],
			:municipio => session[:municipio]
		}
		session[:acao] = nil
		session[:licitacaos_where] = nil
		session[:data_abertura_inicial] = nil
		session[:data_abertura_final] = nil
		session[:filtro] = nil
		session[:municipio] = nil

		begin
			send_data( PDFGenerator.gera_pdf(@licitacaos, dados_da_pesquisa), :type => :pdf)
		rescue Exception
            		gera_lista		    
		end
	end
    def gera_pesquisa
		if params[:page]
            @page = params[:page].to_i
        elsif
            @page = 1
        end
	    if( @licitacaos.size / 10 < @page - 1 )
	    	@page = @licitacaos.size / 10
			@page += 1 if @licitacaos.size % 10 > 0
            if @page > 0    
        		redirect_to "#{root_path}?page=#{@page}"
            elsif
               @page = 1
            end
	    end
		@licitacaos = @licitacaos.paginate( page: @page,  per_page: 10)
		@filtro = Filtro.new(session[:filtro])
    	@data_abertura_inicial = session[:data_abertura_inicial] or ''
    	@data_abertura_final = session[:data_abertura_final] or ''
    	@municipio = session[:municipio] or ''
    end	
	def gera_lista
		session[:acao] = nil
		session[:licitacaos_where] = nil
		session[:data_abertura_inicial] = nil
		session[:data_abertura_final] = nil
		session[:filtro] = nil
        		session[:municipio] = nil
		@licitacaos = Licitacao.where( exibir: true ).order(@@ORDENACAO).paginate(page: params[:page],per_page: 10)	
  		@filtro = Filtro.new
	end    
	def gera_filtro_salvo
        		gera_lista
	end  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<%= javascript_tag "var filtrosJSON = #{@filtros.to_json}; var page = #{@page or 0}"%>
<div id="all">
	<div id="header">
		<div class="navbar">
			<div class="navbar-inner">
				<a class="brand" href="<%= root_path %>" title="Página inicial">Licitações Finder</a>
			</div>
		</div>
	</div>

	<div id="body">
		<div id="form">
			<%= form_for( @filtro, :html => { :class=>"form_inline" } ) do |f|%>
			<fieldset>
				<legend>Pesquisa de licitações</legend>
				<label title="Keywords para pesquisar na coluna Objetos">
					<b><i class="icon-filter"></i> Filtro</b>
				</label>
				<br/>
				<%= f.hidden_field(:descricao) %>
				<%= f.text_field(:keywords,:class=>"input-xxlarge", :placeholder=>"Preencha várias keywords separando por vírgula",  :value => @filtro.keywords || '', :title=>"Preencha várias keywords separando por vírgula") %> ou
				<select id="cmbKeywords" onchange="muda_keywords( this )" title="Selecione um filtro existente">
					<option>Selecione um filtro existente</option>
					<% @filtros.each do |filtro|  %>
						<option><%= filtro.descricao %></option>
					<% end %>
				</select>
				<button type="button" class="btn" onClick="salvar_filtro()" title="Salvar filtro para futuras pesquisas" style="margin-top:-10px;">Salvar filtro</button>
				<br/>
				<br/>
				<label title="Intervalo de datas para pesquisar na coluna Data de Abertura">
					<b><i class="icon-calendar"></i> Data de Abertura</b>
				</label>
				<br/>
				De:
				<input id="data_abertura_inicial" name="data_abertura_inicial" type="text" value="<%= @data_abertura_inicial %>" class="datepicker" title="Preencha a data inicial" placeholder="Preencha a data inicial"/> a 
				<input id="data_abertura_final" name="data_abertura_final" type="text" value="<%= @data_abertura_final %>" class="datepicker" title="Preencha a data final" placeholder="Preencha a data final">
				<br/>
				<br/>
				<label title="Keyword para pesquisar na coluna Município">
					<b><i class="icon-filter"></i> Município</b>
				</label>
				<br/>
				<input id="municipio" name="municipio" type="text" value="<%= @municipio %>" class="input-xxlarge" title="Preencha uma keyword para município" placeholder="Preencha uma keyword para município"/> 
				<br/>
				<br/>
				<button class="btn btn-primary" onClick = "pesquisar()" title="Pesquisar keywords entre as datas informadas"><i class="icon-search icon-white"></i> Pesquisar</button>
			</fieldset>
			<% end %>

			
			<script type="text/javascript">
			
			$('.datepicker').datepicker({
				format: 'dd/mm/yyyy'
			});
			</script>
		</div>
		<%= 
			if @filtro.descricao != nil 
				javascript_tag "document.getElementById('cmbKeywords').value = '#{@filtro.descricao}'"  
			end 
		%>
		<h3>Resultado:</h3>
		<div class="tabela">
			<div class="navbar">
				<div class="navbar-inner">
					<ul class="nav">
						<div class="btn-group">
							<a id="nao_exibir" class="btn dropdown-toggle" onclick="nao_exibir()" title="Não exibir as licitações marcadas."><i class="icon-remove"></i>
								Não exibir

							</a>					
						</div>
						<div class="btn-group ">
							<a class="btn dropdown-toggle" data-toggle="dropdown" href="#" title="Atualizar pelo TCM-CE"><i class="icon-refresh"></i>
								Atualizar
								<span class="caret"></span>
							</a>
							<ul class="dropdown-menu">
								<li>
									<a href="<%= atualiza_tudo_path %>" onclick="greyout()" title="Atualizar de janeiro à dezembro">Atualizar tudo</a>
								</li>
								<li>
									<a href="<%= atualiza_parcial_path %>" onclick="greyout()" title="Atualizar do mês corrente à dezembro">Atualizar parcial</a>
								</li>
							</ul>
						</div>
					</ul>
				</div>
		</div>
			<% if @licitacaos and @licitacaos.length > 0 %>
			<table class="table table-striped table-hover">
				<thead>
					<tr>
					    <th><input type="checkbox" onclick="marcar_desmarcar_todos(this)" title="Marcas ou Desmarcar Todos"/></th>
					    <th>Data de Abertura</th>
					    <th>Município</th>
					    <th>Código</th>
					    <th>Objeto</th>
					    <th>Criado</th>
					    <th>Atualizado</th>
					    <th>Link</th>
					</tr>
				</thead>
				<tbody>
					<% @licitacaos.each do |licitacao| %>
					<tr>
						<td class="checkbox-exibir">
						   <%= check_box_tag licitacao.id , licitacao.exibir?, !licitacao.exibir? %>
						</td>
						<td><%= licitacao.data_abertura.strftime("%d/%m/%Y") %></td>
						<td><%= licitacao.municipio %></td>
						<td><%= licitacao.codigo %></td>
						<td><%= licitacao.objeto %></td>
						<td><%= licitacao.created_at.strftime("%d/%m/%Y") %></td>
						<td><%= licitacao.updated_at.strftime("%d/%m/%Y") %></td>
						<td><a class="btn btn-link" href="<%= licitacao.link %>" target="_blank" title="Abrir licitação no TCM-CE">Abrir</a></td>
					</tr>
					<% end%>
				</tbody>
			</table>
			<%= pagination_links @licitacaos %>
			<% else %>
				<h4>A busca não obteve resultados.</h4>
			<% end %>

		</div>
          
		<div id="footer">
			<p class="lead pull-right pdf_link">Exportar para: 
			    <a href="<%= xls_path %>?data_abertura_inicial=<%= @data_abertura_inicial %>&data_abertura_final=<%= @data_abertura_final %>&filtro[keywords]=<%= @filtro.keywords %>&municipio=<%= @municipio %>&formato=xls" class="btn btn-success">XLS</a>
				<a href="<%= pdf_path %>?data_abertura_inicial=<%= @data_abertura_inicial %>&data_abertura_final=<%= @data_abertura_final %>&filtro[keywords]=<%= @filtro.keywords %>&municipio=<%= @municipio %>&formato=pdf" " class="btn btn-danger muted">PDF</a>
			</p>

		</div>
	</div>

</div>